
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author ruflas
 */
public class DatosProducto extends javax.swing.JDialog {

    /**
     * Creates new form DatosProducto
     */
    private DatosProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargaTipoProductos();
    }

    public DatosProducto(Admin VAdmin) {
        this(null, true);
        this.setIconImage(new ImageIcon("src/images/logo.png").getImage());
        POK = false;
        this.VAdmin = VAdmin;
    }

    public boolean showDialog() {
        POK = false;
        TFNombre.setText("");
        setVisible(true);
        return POK;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BCancel = new javax.swing.JButton();
        BOk = new javax.swing.JButton();
        TFNombre = new javax.swing.JTextField();
        TFPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFOferta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBTipoProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAEspecificaciones = new javax.swing.JTextArea();
        LChipset = new javax.swing.JLabel();
        TFChipset = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos Producto");

        jLabel1.setText("Nombre:");

        BCancel.setText("Cancelar");
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });

        BOk.setText("Aceptar");
        BOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOkActionPerformed(evt);
            }
        });

        TFPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFPrecioKeyTyped(evt);
            }
        });

        jLabel2.setText("Precio:");

        jLabel4.setText("Oferta:");

        TFOferta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFOfertaKeyTyped(evt);
            }
        });

        jLabel5.setText("Tipo:");

        CBTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTipoProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Especificaciones:");

        TAEspecificaciones.setColumns(20);
        TAEspecificaciones.setRows(5);
        jScrollPane1.setViewportView(TAEspecificaciones);

        LChipset.setText("Chipset:");
        LChipset.setEnabled(false);

        TFChipset.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(BOk)
                .addGap(76, 76, 76)
                .addComponent(BCancel)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LChipset)
                        .addGap(18, 18, 18)
                        .addComponent(TFChipset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFPrecio)
                            .addComponent(TFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(TFOferta)
                            .addComponent(CBTipoProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LChipset)
                    .addComponent(TFChipset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOk)
                    .addComponent(BCancel))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_BCancelActionPerformed

    private void BOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOkActionPerformed
        // TODO add your handling code here:
        if (TFNombre.getText().length() > 0 && TFOferta.getText().length() > 0 && TFPrecio.getText().length() > 0) {
            if (!(Double.parseDouble(TFOferta.getText()) >= 0 && Double.parseDouble(TFOferta.getText()) < 1)) {
                JOptionPane.showMessageDialog(null, "Oferta debe ser mayor o igual que 0 y menor que 1.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if ((CBTipoProducto.getSelectedItem().equals("CPU") || CBTipoProducto.getSelectedItem().equals("Motherboard")) && TFChipset.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Debes introducir el chipset.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    POK = true;
                    TipoProducto tipo = TipoProducto.valueOf("" + CBTipoProducto.getSelectedItem());
                    System.out.println(tipo);
                    if (tipo.equals(TipoProducto.CPU) || tipo.equals(TipoProducto.Motherboard)){
                         VAdmin.setDatosProducto(TFNombre.getText(), Double.parseDouble(TFPrecio.getText()), Double.parseDouble(TFOferta.getText()), tipo, TAEspecificaciones.getText(), TFChipset.getText());
                    }
                    else{
                        System.out.print("Vaya me he librado pero sigue sin ir siendo tipo "+tipo);
                        VAdmin.setDatosProducto(TFNombre.getText(), Double.parseDouble(TFPrecio.getText()), Double.parseDouble(TFOferta.getText()), tipo, TAEspecificaciones.getText(),"");
                    }
                    this.dispose();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BOkActionPerformed

    private void TFPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFPrecioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_TFPrecioKeyTyped

    private void TFOfertaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFOfertaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_TFOfertaKeyTyped

    private void CBTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTipoProductoActionPerformed
        // TODO add your handling code here:
        if (CBTipoProducto.getSelectedItem().equals("CPU") || CBTipoProducto.getSelectedItem().equals("Motherboard")) {
            LChipset.setEnabled(true);
            TFChipset.setEnabled(true);
        } else {
            LChipset.setEnabled(false);
            TFChipset.setEnabled(false);
        }
    }//GEN-LAST:event_CBTipoProductoActionPerformed

    private void cargaTipoProductos() {
        for (TipoProducto tipo : TipoProducto.values()) {
            CBTipoProducto.addItem(tipo.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatosProducto dialog = new DatosProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private boolean POK;
    Admin VAdmin;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancel;
    private javax.swing.JButton BOk;
    private javax.swing.JComboBox<String> CBTipoProducto;
    private javax.swing.JLabel LChipset;
    private javax.swing.JTextArea TAEspecificaciones;
    private javax.swing.JTextField TFChipset;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFOferta;
    private javax.swing.JTextField TFPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
