
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ruflas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Login() {
        initComponents();
        this.setIconImage(new ImageIcon("src/images/logo.png").getImage());
    }

    public Login(Principal VPrincipal) {
        this();
        this.VPrincipal = VPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFUser = new javax.swing.JTextField();
        BLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PFPassword = new javax.swing.JPasswordField();
        TBVisible = new javax.swing.JToggleButton();
        BGoogle = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TBRegister = new javax.swing.JToggleButton();
        LExit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        BLogin.setText("Sing in");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        TBVisible.setBackground(new java.awt.Color(60, 63, 65));
        TBVisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        TBVisible.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hidden.png"))); // NOI18N
        TBVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBVisibleActionPerformed(evt);
            }
        });

        BGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        BGoogle.setText("Google");
        BGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGoogleActionPerformed(evt);
            }
        });

        jLabel4.setText("or");

        jLabel5.setText("If you are not registered click here:");

        TBRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify.png"))); // NOI18N
        TBRegister.setText("Register");
        TBRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBRegisterActionPerformed(evt);
            }
        });

        LExit.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrarapp.png"))); // NOI18N
        LExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LExitMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LExit)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(PFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(TBVisible))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(BLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(BGoogle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(TBRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(TFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(LExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(TFUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(PFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TBVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(BLogin)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(BGoogle)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(TBRegister)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TBVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBVisibleActionPerformed
        boolean passwordVisible = TBVisible.isSelected();
        if (passwordVisible) {
            PFPassword.setEchoChar((char) 0);
            passwordVisible = true;
        } else {
            PFPassword.setEchoChar('*');
            passwordVisible = false;
        }
    }//GEN-LAST:event_TBVisibleActionPerformed

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        // TODO add your handling code here:
        char[] password = PFPassword.getPassword();
        String passwordString = new String(password);
        if (TFUser.getText().length() > 0 && passwordString.length() > 0) {
            boolean succes = login(TFUser.getText(), passwordString);
            if (succes) {
                String user = TFUser.getText();
                usuario = new Usuario(user, passwordString);
                VPrincipal.setUsuario(this.usuario);
                VCarga = new Carga(VPrincipal);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Inicio de sesión fallido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BLoginActionPerformed

    private void TBRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBRegisterActionPerformed
        // TODO add your handling code here:
        TBRegister.setEnabled(false);
        VRegister = new Register(this);
        VRegister.setVisible(true);
    }//GEN-LAST:event_TBRegisterActionPerformed

    private void BGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGoogleActionPerformed
        // TODO add your handling code here:
        BGoogle.setEnabled(false);
        VGAuth = new GoogleAuth(this);
        VGAuth.setVisible(true);
    }//GEN-LAST:event_BGoogleActionPerformed

    private void LExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LExitMouseClicked

    public void enableRegister() {
        TBRegister.setEnabled(true);
    }

    public void enableGAuth() {
        BGoogle.setEnabled(true);
    }

    public void gAuthSuccess(String user, String password) {
        Register.register(user, password);
        usuario = new Usuario(user, password);
        VPrincipal.setUsuario(this.usuario);
        VPrincipal.setVisible(true);
        this.setVisible(false);
    }

    public boolean login(String user, String password) {
        String archivo = "usuarios.txt";
        System.out.println(user + ":" + password);
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(":");
                if (partes[0].equals(user) && partes[1].equals(password)) {
                    return true;
                }
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo " + archivo);
            e.printStackTrace();
        }

        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    Principal VPrincipal;
    Register VRegister;
    GoogleAuth VGAuth;
    Usuario usuario;
    Carga VCarga;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGoogle;
    private javax.swing.JButton BLogin;
    private javax.swing.JLabel LExit;
    private javax.swing.JPasswordField PFPassword;
    private javax.swing.JToggleButton TBRegister;
    private javax.swing.JToggleButton TBVisible;
    private javax.swing.JTextField TFUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
