
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ruflas
 */
public class Pago extends javax.swing.JFrame {

    /**
     * Creates new form Pago
     */
    private Pago() {
        initComponents();
        this.setIconImage(new ImageIcon("src/images/logo.png").getImage());
        loadYearCB();
        this.CBMonth.setVisible(false);
        this.CBYear.setVisible(false);
        this.TFCVV.setVisible(false);
        this.LCVV.setVisible(false);
        this.LFecha.setVisible(false);
    }

    public Pago(Carrito VCarrito) {
        this();
        this.VCarrito = VCarrito;
    }

    public static LocalDate getFechaActual() {
        return LocalDate.now();
    }

    public void loadYearCB() {
        int yearNumber = getFechaActual().getYear();
        for (int i = 0; i < 10; i++) {
            String year = ("" + yearNumber).substring(2, 4);
            yearNumber++;
            CBYear.addItem(year);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGPago = new javax.swing.ButtonGroup();
        BGEnvioRecogida = new javax.swing.ButtonGroup();
        CBTarjeta = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBBitcoin = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFPago = new javax.swing.JTextField();
        CBMonth = new javax.swing.JComboBox<>();
        CBYear = new javax.swing.JComboBox<>();
        TFCVV = new javax.swing.JTextField();
        LFecha = new javax.swing.JLabel();
        LCVV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RBEnvio = new javax.swing.JRadioButton();
        RBRecogida = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        TFCodDescuento = new javax.swing.JTextField();
        BPago = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BImporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAImporte = new javax.swing.JTextArea();
        BCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago");
        setResizable(false);

        BGPago.add(CBTarjeta);
        CBTarjeta.setText("Tarjeta");
        CBTarjeta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CBTarjetaStateChanged(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MasterCard_Logo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visa.png"))); // NOI18N

        BGPago.add(CBBitcoin);
        CBBitcoin.setText("Bitcoin");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bitcoin.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel4.setText("Selecciona el método de pago:");

        CBMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        TFCVV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFCVVKeyTyped(evt);
            }
        });

        LFecha.setText("Fecha de caducidad");

        LCVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cvv.png"))); // NOI18N
        LCVV.setText("CVV");

        jLabel7.setText("Num de Tarjeta/Dirección Ingreso Bitcoin");

        jLabel5.setText("Seleccione una opción:");

        BGEnvioRecogida.add(RBEnvio);
        RBEnvio.setText("Envio");

        BGEnvioRecogida.add(RBRecogida);
        RBRecogida.setText("Recogida en tienda");

        jLabel6.setText("Código de descuento:");

        BPago.setBackground(new java.awt.Color(204, 102, 0));
        BPago.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        BPago.setForeground(new java.awt.Color(255, 255, 255));
        BPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pago.png"))); // NOI18N
        BPago.setText("Realizar Pago");
        BPago.setEnabled(false);
        BPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPagoActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BImporte.setBackground(new java.awt.Color(204, 102, 0));
        BImporte.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        BImporte.setForeground(new java.awt.Color(255, 255, 255));
        BImporte.setText("Calcular Importe");
        BImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BImporteActionPerformed(evt);
            }
        });

        TAImporte.setEditable(false);
        TAImporte.setBackground(new java.awt.Color(255, 255, 255));
        TAImporte.setColumns(20);
        TAImporte.setForeground(new java.awt.Color(0, 0, 0));
        TAImporte.setRows(5);
        jScrollPane1.setViewportView(TAImporte);

        BCancel.setBackground(new java.awt.Color(255, 0, 51));
        BCancel.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        BCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/detener.png"))); // NOI18N
        BCancel.setText("Cancel");
        BCancel.setEnabled(false);
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CBTarjeta)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1)))
                                    .addGap(83, 83, 83)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLabel3))
                                        .addComponent(CBBitcoin)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addComponent(LFecha))
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TFPago, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(CBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TFCodDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(RBRecogida)
                                                    .addComponent(RBEnvio)))
                                            .addComponent(jLabel5))
                                        .addGap(4, 4, 4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TFCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LCVV)))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BImporte)
                        .addGap(79, 79, 79)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(BCancel)
                        .addGap(43, 43, 43)
                        .addComponent(BPago)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBTarjeta)
                    .addComponent(CBBitcoin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(9, 9, 9)
                .addComponent(TFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(LFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBEnvio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBRecogida)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TFCodDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(BImporte)
                .addGap(17, 17, 17))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPago)
                    .addComponent(BCancel))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CBTarjetaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CBTarjetaStateChanged
        // TODO add your handling code here:
        if (this.CBTarjeta.isSelected()) {
            this.CBMonth.setVisible(true);
            this.CBYear.setVisible(true);
            this.TFCVV.setVisible(true);
            this.LCVV.setVisible(true);
            this.LFecha.setVisible(true);
        } else {
            this.CBMonth.setVisible(false);
            this.CBYear.setVisible(false);
            this.TFCVV.setVisible(false);
            this.LCVV.setVisible(false);
            this.LFecha.setVisible(false);
        }
    }//GEN-LAST:event_CBTarjetaStateChanged

    private void TFCVVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCVVKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) || this.TFCVV.getText().length() > 2) {
            evt.consume();
        }
    }//GEN-LAST:event_TFCVVKeyTyped

    public void setCiclos(int ciclos){
        this.ciclos = ciclos;
    }
    
    private void BImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BImporteActionPerformed
        // TODO add your handling code here:
        BCancel.setEnabled(true);
        BPago.setEnabled(true);
        this.setCiclos(10);
        this.tarea(this.ciclos);
    }//GEN-LAST:event_BImporteActionPerformed

    public void tarea(int ciclos) {
        boolean error = false;
        if (!TFPago.getText().isEmpty()) {
            if ((CBTarjeta.isSelected() && !TFCVV.getText().isEmpty()) || CBBitcoin.isSelected()) {
                if (RBEnvio.isSelected() || RBRecogida.isSelected()) {
                    this.stop = false;
                    TAImporte.setText("");
                    HiloBack = new Thread() {
                        public void run() {
                            double rand = (Math.random() + 1) * Math.random() * 5, total = 0;
                            int i = 0;
                            while (i < ciclos) {
                                try {
                                    Thread.sleep((int) (0.3 * 1000));
                                } catch (java.lang.InterruptedException E) {
                                }
                                if (Stop()) // El interfaz informa al proceso
                                {
                                    break;
                                }
                                if (i == 0) {
                                    TAImporte.setText(TAImporte.getText() + "Importe carrito: " + String.format("%.2f", VCarrito.precioCarrito()));
                                    total += VCarrito.precioCarrito();
                                } else if (i == (int) ciclos*0.2) {
                                    if (RBEnvio.isSelected()) {
                                        TAImporte.setText(TAImporte.getText() + "\nEnvio: " + String.format("%.2f", rand));
                                        total += rand;
                                    } else {
                                        TAImporte.setText(TAImporte.getText() + "\nRecogida: " + 0);
                                    }
                                } else if (i == (int) ciclos*0.7) {
                                    if (TFCodDescuento.getText().equals("-10")) {
                                        TAImporte.setText(TAImporte.getText() + "\nDescuento: -10%");
                                        total = total - (total * 0.1);
                                    } else {
                                        TAImporte.setText(TAImporte.getText() + "\nDescuento: NO APLICADO");
                                    }
                                } else if (i == (int) ciclos*0.9) {
                                    TAImporte.setText(TAImporte.getText() + "\nTotal: " + String.format("%.2f €", total));
                                }
                                i++;
                            }
                        }
                    };
                    HiloBack.start();
                } else {
                    error = true;
                }
            } else {
                error = true;
            }
        } else {
            error = true;
        }
        if (error) {
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean Stop() {
        return this.stop;
    }

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        this.stop = true;
        this.BCancel.setEnabled(false);
    }//GEN-LAST:event_BCancelActionPerformed

    public String paymentMethod() {
        if (CBBitcoin.isSelected()) {
            return "Bitcoin";
        }
        return "Card";
    }

    private void BPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPagoActionPerformed
        // TODO add your handling code here:
        this.textoFactura = this.VCarrito.getTextCarrito() + "\n" + TAImporte.getText();
        PaymentConfirm VPC = new PaymentConfirm(this);
        VPC.setVisible(true);
    }//GEN-LAST:event_BPagoActionPerformed

    public String getTextoFactura() {
        if (this.textoFactura != null) {
            return this.textoFactura;
        }
        return "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pago().setVisible(true);
            }
        });
    }
    Carrito VCarrito;
    private Thread HiloBack;
    private boolean stop = false;
    public String textoFactura;
    private int ciclos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancel;
    private javax.swing.ButtonGroup BGEnvioRecogida;
    private javax.swing.ButtonGroup BGPago;
    private javax.swing.JButton BImporte;
    private javax.swing.JButton BPago;
    private javax.swing.JCheckBox CBBitcoin;
    private javax.swing.JComboBox<String> CBMonth;
    private javax.swing.JCheckBox CBTarjeta;
    private javax.swing.JComboBox<String> CBYear;
    private javax.swing.JLabel LCVV;
    private javax.swing.JLabel LFecha;
    private javax.swing.JRadioButton RBEnvio;
    private javax.swing.JRadioButton RBRecogida;
    private javax.swing.JTextArea TAImporte;
    private javax.swing.JTextField TFCVV;
    private javax.swing.JTextField TFCodDescuento;
    private javax.swing.JTextField TFPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
